name: DevOps-GitHubActions

on: push

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # Fetch only the latest commit

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm' # Cache dependencies

      - name: Install Dependencies
        run: npm install --force --verbose

      - name: Build Project
        run: npm run build
